insert into category values (1, null, null);
insert into category values (2, null, null);
insert into category values (3, null, null);
insert into category values (4, null, null);
insert into category values (5, 1, null);
insert into category values (6, 1, null);
insert into category values (7, 1, null);
insert into category values (8, 1, null);
insert into category values (9, 2, null);
insert into category values (10, 2, null);
insert into category values (11, 2, null);
insert into category values (12, 2, null);
insert into category values (13, 3, null);
insert into category values (14, 3, null);
insert into category values (15, 3, null);
insert into category values (16, 3, null);
insert into category values (17, 4, null);
insert into category values (18, 4, null);
insert into category values (19, 4, null);
insert into category values (20, 4, null);

insert into product values (1, 23.90, 10, 5, null);
insert into product values (2, 25.90, 20, 6, null);
insert into product values (3, 16.90, 5, 7, null);
insert into product values (4, 15.90, 30, 8, null);
insert into product values (5, 19.99, 3, 9, null);
insert into product values (6, 30.95, 3, 10, null);
insert into product values (7, 14.95, 30, 11, null);
insert into product values (8, 84.95, 15, 12, null);
insert into product values (9, 15.99, 10, 13, null);
insert into product values (10, 45.99, 15, 14, null);
insert into product values (11, 5.99, 40, 15, null);
insert into product values (12, 39.09, 5, 16, null);
insert into product values (13, 15.00, 5, 17, null);
insert into product values (14, 35.00, 5, 18, null);
insert into product values (15, 16.50, 5, 19, null);
insert into product values (16, 45.00, 5, 20, null);

insert into product_feature values (1, "Proporciona calidez y comodidad durante todo el día", "es", 1);
insert into product_feature values (1, "Provides warmth and comfort throughout the day", "en", 1);
insert into product_feature values (2, "Ideal para climas frescos", "es", 1);
insert into product_feature values (2, "Perfect for cool climates", "en", 1);
insert into product_feature values (3, "Fabricada con materiales de alta calidad", "es", 1);
insert into product_feature values (3, "Made with high-quality materials", "en", 1);
insert into product_feature values (4, "Diseño moderno y versátil", "es", 1);
insert into product_feature values (4, "Modern and versatile design", "en", 1);
insert into product_feature values (5, "Capucha ajustable y bolsillos funcionales", "es", 1);
insert into product_feature values (5, "Adjustable hood and functional pockets", "en", 1);
insert into product_feature values (6, "Disponible en varios colores", "es", 1);
insert into product_feature values (6, "Available in multiple colors", "en", 1);
insert into product_feature values (7, "Talla: unisex", "es", 1);
insert into product_feature values (7, "Size: unisex", "en", 1);
insert into product_feature values (8, "Tejido transpirable que proporciona una buena ventilación", "es", 1);
insert into product_feature values (8, "Breathable fabric that provides good ventilation", "en", 1);
insert into product_feature values (1, "Protege el cuerpo entero de humedad, suciedad y frío en temperaturas muy bajas", "es", 2);
insert into product_feature values (1, "Protects the entire body from moisture, dirt and cold", "en", 2);
insert into product_feature values (2, "Especialmente recomendable para perros de pelo corto", "es", 2);
insert into product_feature values (2, "Recommended for short-haired dogs", "en", 2);
insert into product_feature values (3, "Impermeable y protegido contra el viento pero de membrana transpirable", "es", 2);
insert into product_feature values (3, "Waterproof and windproof", "en", 2);
insert into product_feature values (4, "Con forro suave de felpa y acolchado (poliéster)", "es", 2);
insert into product_feature values (4, "With soft fleece lining and padding (polyester)", "en", 2);
insert into product_feature values (5, "Costuras selladas y cremallera impermeable", "es", 2);
insert into product_feature values (5, "Taped seams and waterproof zipper", "en", 2);
insert into product_feature values (6, "Puede combinarse con arnés", "es", 2);
insert into product_feature values (6, "Can be combined with harness", "en", 2);
insert into product_feature values (7, "Ajuste perfecto por las inserciones elásticas, cordones y cinta de cierre", "es", 2);
insert into product_feature values (7, "Perfect fit due to elastic inserts, laces and closure tape", "en", 2);
insert into product_feature values (8, "Color: amarillo", "es", 2);
insert into product_feature values (8, "Colour: yellow", "en", 2);
insert into product_feature values (1, "Protege las patas del perro de la humedad, el calor y las superficies ásperas", "es", 3);
insert into product_feature values (1, "Protects the dog's paws from moisture, heat, and rough surfaces", "en", 3);
insert into product_feature values (2, "Suela resistente y antideslizante para mayor tracción", "es", 3);
insert into product_feature values (2, "Durable and non-slip sole for enhanced traction", "en", 3);
insert into product_feature values (3, "Fácil de poner y quitar con cierre de velcro ajustable", "es", 3);
insert into product_feature values (3, "Easy to put on and take off with adjustable velcro closure", "en", 3);
insert into product_feature values (4, "Material duradero y lavable para un uso prolongado", "es", 3);
insert into product_feature values (4, "Durable and washable material for long-lasting use", "en", 3);
insert into product_feature values (5, "Disponible en diferentes tamaños para adaptarse a las patas de tu perro", "es", 3);
insert into product_feature values (5, "Available in different sizes to fit your dog's paws", "en", 3);
insert into product_feature values (6, "Protege las almohadillas de las patas de tu perro durante caminatas largas", "es", 3);
insert into product_feature values (6, "Protects your dog's paw pads during long walks", "en", 3);
insert into product_feature values (7, "Diseñadas con tejido transpirable para evitar la acumulación de calor", "es", 3);
insert into product_feature values (7, "Designed with breathable fabric to prevent heat buildup", "en", 3);
insert into product_feature values (8, "Costuras reforzadas para mayor durabilidad y resistencia", "es", 3);
insert into product_feature values (8, "Reinforced stitching for durability and strength", "en", 3);
insert into product_feature values (1, "Proporciona calidez y comodidad durante todo el día", "es", 4);
insert into product_feature values (1, "Provides warmth and comfort throughout the day", "en", 4);
insert into product_feature values (2, "Ideal para climas frescos", "es", 4);
insert into product_feature values (2, "Perfect for cool climates", "en", 4);
insert into product_feature values (3, "Fabricada con materiales de alta calidad", "es", 4);
insert into product_feature values (3, "Made with high-quality materials", "en", 4);
insert into product_feature values (4, "Diseño moderno y versátil", "es", 4);
insert into product_feature values (4, "Modern and versatile design", "en", 4);
insert into product_feature values (5, "Capucha ajustable y bolsillos funcionales", "es", 4);
insert into product_feature values (5, "Adjustable hood and functional pockets", "en", 4);
insert into product_feature values (6, "Disponible en varios colores", "es", 4);
insert into product_feature values (6, "Available in multiple colors", "en", 4);
insert into product_feature values (7, "Talla: unisex", "es", 4);
insert into product_feature values (7, "Size: unisex", "en", 4);
insert into product_feature values (8, "Tejido transpirable que proporciona una buena ventilación", "es", 4);
insert into product_feature values (8, "Breathable fabric that provides good ventilation", "en", 4);
insert into product_feature values (1, "Correa diseñada específicamente para actividades de running con tu perro", "es", 5);
insert into product_feature values (1, "Leash specifically designed for running activities with your dog", "en", 5);
insert into product_feature values (2, "Fabricada con materiales resistentes y duraderos", "es", 5);
insert into product_feature values (2, "Made with sturdy and durable materials", "en", 5);
insert into product_feature values (3, "Longitud ajustable para adaptarse a diferentes tamaños de perro", "es", 5);
insert into product_feature values (3, "Adjustable length to fit different dog sizes", "en", 5);
insert into product_feature values (4, "Cierre de seguridad para una sujeción firme y segura", "es", 5);
insert into product_feature values (4, "Safety closure for a firm and secure grip", "en", 5);
insert into product_feature values (5, "Mango acolchado para mayor comodidad durante la actividad", "es", 5);
insert into product_feature values (5, "Padded handle for added comfort during the activity", "en", 5);
insert into product_feature values (6, "Reflectante para una mejor visibilidad en condiciones de poca luz", "es", 5);
insert into product_feature values (6, "Reflective for better visibility in low-light conditions", "en", 5);
insert into product_feature values (7, "Ligera y fácil de llevar durante tus carreras", "es", 5);
insert into product_feature values (7, "Lightweight and easy to carry during your runs", "en", 5);
insert into product_feature values (8, "Diseño ergonómico que reduce la tensión en las manos", "es", 5);
insert into product_feature values (8, "Ergonomic design that reduces strain on the hands", "en", 5);
insert into product_feature values (1, "Permite acoplar una cámara GoPro al arnés de tu perro para capturar aventuras desde su perspectiva", "es", 6);
insert into product_feature values (1, "Allows you to attach a GoPro camera to your dog's harness to capture adventures from their perspective", "en", 6);
insert into product_feature values (2, "Diseñado para brindar comodidad y seguridad a tu perro durante la grabación", "es", 6);
insert into product_feature values (2, "Designed to provide comfort and safety for your dog during recording", "en", 6);
insert into product_feature values (3, "Ajustable para adaptarse a diferentes tamaños de perro", "es", 6);
insert into product_feature values (3, "Adjustable to fit different dog sizes", "en", 6);
insert into product_feature values (4, "Material resistente y duradero para un uso prolongado", "es", 6);
insert into product_feature values (4, "Sturdy and durable material for long-lasting use", "en", 6);
insert into product_feature values (5, "Sujeción segura que mantiene la cámara estable durante la actividad", "es", 6);
insert into product_feature values (5, "Secure attachment that keeps the camera stable during activity", "en", 6);
insert into product_feature values (6, "Correas ajustables para un ajuste cómodo y seguro", "es", 6);
insert into product_feature values (6, "Adjustable straps for a comfortable and secure fit", "en", 6);
insert into product_feature values (7, "Ligero y no causa molestias ni restricciones al perro", "es", 6);
insert into product_feature values (7, "Lightweight and does not cause discomfort or restrictions to the dog", "en", 6);
insert into product_feature values (8, "Permite capturar momentos únicos y emocionantes desde la perspectiva de tu perro", "es", 6);
insert into product_feature values (8, "Allows you to capture unique and exciting moments from your dog's perspective", "en", 6);
insert into product_feature values (1, "Collar luminoso que proporciona visibilidad adicional durante paseos nocturnos", "es", 7);
insert into product_feature values (1, "Luminous collar that provides additional visibility during nighttime walks", "en", 7);
insert into product_feature values (2, "Visible a distancia para mayor seguridad en áreas con poca iluminación", "es", 7);
insert into product_feature values (2, "Visible from a distance for enhanced safety in low-light areas", "en", 7);
insert into product_feature values (3, "Diseño ajustable para adaptarse al tamaño del cuello de tu perro", "es", 7);
insert into product_feature values (3, "Adjustable design to fit your dog's neck size", "en", 7);
insert into product_feature values (4, "Función de luz intermitente para una mayor atención", "es", 7);
insert into product_feature values (4, "Flashing light function for increased attention", "en", 7);
insert into product_feature values (5, "Batería recargable que garantiza un uso duradero", "es", 7);
insert into product_feature values (5, "Rechargeable battery that ensures long-lasting use", "en", 7);
insert into product_feature values (6, "Fabricado con materiales de alta calidad para mayor durabilidad", "es", 7);
insert into product_feature values (6, "Made with high-quality materials for enhanced durability", "en", 7);
insert into product_feature values (7, "Cómodo de llevar y no causa molestias al perro", "es", 7);
insert into product_feature values (7, "Comfortable to wear and does not cause discomfort to the dog", "en", 7);
insert into product_feature values (8, "Fácil de encender y apagar con un simple botón", "es", 7);
insert into product_feature values (8, "Easy to turn on and off with a simple button", "en", 7);
insert into product_feature values (1, "Collar para perro con sistema GPS integrado para rastreo en tiempo real", "es", 8);
insert into product_feature values (1, "Dog collar with built-in GPS system for real-time tracking", "en", 8);
insert into product_feature values (2, "Localiza a tu perro en caso de pérdida o robo", "es", 8);
insert into product_feature values (2, "Locate your dog in case of loss or theft", "en", 8);
insert into product_feature values (3, "Alertas y notificaciones en tu teléfono móvil para mayor tranquilidad", "es", 8);
insert into product_feature values (3, "Alerts and notifications on your mobile phone for peace of mind", "en", 8);
insert into product_feature values (4, "Geovalla virtual para delimitar áreas seguras y recibir alertas si tu perro las abandona", "es", 8);
insert into product_feature values (4, "Virtual geofence to define safe areas and receive alerts if your dog leaves them", "en", 8);
insert into product_feature values (5, "Registro de actividad para conocer el nivel de actividad física de tu perro", "es", 8);
insert into product_feature values (5, "Activity log to track your dog's physical activity level", "en", 8);
insert into product_feature values (6, "Resistente al agua y diseñado para resistir el uso diario", "es", 8);
insert into product_feature values (6, "Waterproof and designed to withstand daily use", "en", 8);
insert into product_feature values (7, "Aplicación móvil fácil de usar con interfaz intuitiva", "es", 8);
insert into product_feature values (7, "Easy-to-use mobile application with an intuitive interface", "en", 8);
insert into product_feature values (8, "Batería de larga duración para un seguimiento continuo", "es", 8);
insert into product_feature values (8, "Long-lasting battery for continuous tracking", "en", 8);
insert into product_feature values (1, "Casco de moto diseñado específicamente para perros", "es", 9);
insert into product_feature values (1, "Motorcycle helmet specifically designed for dogs", "en", 9);
insert into product_feature values (2, "Protección óptima para la cabeza y los ojos de tu perro durante paseos en moto", "es", 9);
insert into product_feature values (2, "Optimal protection for your dog's head and eyes during motorcycle rides", "en", 9);
insert into product_feature values (3, "Correas ajustables para un ajuste seguro y cómodo", "es", 9);
insert into product_feature values (3, "Adjustable straps for a secure and comfortable fit", "en", 9);
insert into product_feature values (4, "Hecho de materiales resistentes y duraderos", "es", 9);
insert into product_feature values (4, "Made from sturdy and durable materials", "en", 9);
insert into product_feature values (5, "Ventilación adecuada para mayor comodidad durante los paseos en moto", "es", 9);
insert into product_feature values (5, "Proper ventilation for enhanced comfort during motorcycle rides", "en", 9);
insert into product_feature values (6, "Visera desmontable para proteger los ojos de tu perro del viento y los desechos", "es", 9);
insert into product_feature values (6, "Removable visor to protect your dog's eyes from wind and debris", "en", 9);
insert into product_feature values (7, "Diseño moderno y llamativo para destacar en la carretera", "es", 9);
insert into product_feature values (7, "Modern and eye-catching design to stand out on the road", "en", 9);
insert into product_feature values (8, "Disponible en diferentes tamaños para adaptarse a perros de distintas razas", "es", 9);
insert into product_feature values (8, "Available in different sizes to fit dogs of various breeds", "en", 9);
insert into product_feature values (1, "Mochila espaciosa y cómoda para transportar a tu mascota con facilidad", "es", 10);
insert into product_feature values (1, "Spacious and comfortable backpack for transporting your pet with ease", "en", 10);
insert into product_feature values (2, "Diseño ergonómico que proporciona soporte y comodidad tanto para ti como para tu mascota", "es", 10);
insert into product_feature values (2, "Ergonomic design that provides support and comfort for both you and your pet", "en", 10);
insert into product_feature values (3, "Ventanas de malla transpirable para una buena circulación de aire", "es", 10);
insert into product_feature values (3, "Breathable mesh windows for good air circulation", "en", 10);
insert into product_feature values (4, "Correas ajustables y acolchadas para un ajuste seguro y confortable", "es", 10);
insert into product_feature values (4, "Adjustable and padded straps for a secure and comfortable fit", "en", 10);
insert into product_feature values (5, "Bolsillos y compartimentos adicionales para llevar objetos esenciales durante el paseo", "es", 10);
insert into product_feature values (5, "Additional pockets and compartments for carrying essential items during the walk", "en", 10);
insert into product_feature values (6, "Resistente y duradera, diseñada para un uso a largo plazo", "es", 10);
insert into product_feature values (6, "Sturdy and durable, designed for long-term use", "en", 10);
insert into product_feature values (7, "Cierre de seguridad para garantizar que tu mascota esté siempre protegida", "es", 10);
insert into product_feature values (7, "Safety lock to ensure your pet is always protected", "en", 10);
insert into product_feature values (8, "Disponible en diferentes tamaños y colores para adaptarse a tus preferencias", "es", 10);
insert into product_feature values (8, "Available in different sizes and colors to suit your preferences", "en", 10);
insert into product_feature values (1, "Mantiene a tu perro seguro y protegido durante los viajes en coche", "es", 11);
insert into product_feature values (1, "Keeps your dog safe and secure during car rides", "en", 11);
insert into product_feature values (2, "Diseñado para evitar que tu perro se mueva demasiado y cause distracciones", "es", 11);
insert into product_feature values (2, "Designed to prevent your dog from moving too much and causing distractions", "en", 11);
insert into product_feature values (3, "Hebilla ajustable que se adapta a diferentes tamaños de perro", "es", 11);
insert into product_feature values (3, "Adjustable buckle that fits different dog sizes", "en", 11);
insert into product_feature values (4, "Fabricado con materiales duraderos y resistentes para una mayor seguridad", "es", 11);
insert into product_feature values (4, "Made with durable and sturdy materials for enhanced safety", "en", 11);
insert into product_feature values (5, "Fácil de instalar y utilizar, sin necesidad de herramientas adicionales", "es", 11);
insert into product_feature values (5, "Easy to install and use, no additional tools required", "en", 11);
insert into product_feature values (6, "Permite que tu perro se siente, pare y se acueste cómodamente durante el viaje", "es", 11);
insert into product_feature values (6, "Allows your dog to sit, stand, and lie down comfortably during the trip", "en", 11);
insert into product_feature values (7, "Seguro y confiable, cumple con los estándares de seguridad en carretera", "es", 11);
insert into product_feature values (7, "Safe and reliable, meets road safety standards", "en", 11);
insert into product_feature values (8, "Compatible con la mayoría de los cinturones de seguridad en los coches", "es", 11);
insert into product_feature values (8, "Compatible with most seat belts in cars", "en", 11);
insert into product_feature values (1, "Proporciona a tu perro un lugar cómodo y seguro en el coche", "es", 12);
insert into product_feature values (1, "Provides your dog with a comfortable and secure place in the car", "en", 12);
insert into product_feature values (2, "Eleva a tu perro para que pueda ver por la ventana durante el viaje", "es", 12);
insert into product_feature values (2, "Elevates your dog so they can see out the window during the trip", "en", 12);
insert into product_feature values (3, "Diseñado con materiales acolchados y suaves para mayor comodidad", "es", 12);
insert into product_feature values (3, "Designed with padded and soft materials for enhanced comfort", "en", 12);
insert into product_feature values (4, "Fácil de instalar y asegurar en el asiento del coche", "es", 12);
insert into product_feature values (4, "Easy to install and secure on the car seat", "en", 12);
insert into product_feature values (5, "Cinturón de seguridad incorporado para mantener a tu perro sujeto", "es", 12);
insert into product_feature values (5, "Built-in safety belt to keep your dog securely fastened", "en", 12);
insert into product_feature values (6, "Amplio espacio para que tu perro se mueva y se acomode cómodamente", "es", 12);
insert into product_feature values (6, "Ample space for your dog to move around and comfortably settle", "en", 12);
insert into product_feature values (7, "Protege el asiento del coche de pelos, suciedad y rasguños", "es", 12);
insert into product_feature values (7, "Protects the car seat from fur, dirt, and scratches", "en", 12);
insert into product_feature values (8, "Adecuado para perros de diferentes tamaños y razas", "es", 12);
insert into product_feature values (8, "Suitable for dogs of different sizes and breeds", "en", 12);
insert into product_feature values (1, "Botella de agua y cuenco integrado para mantener a tu perro hidratado", "es", 13);
insert into product_feature values (1, "Integrated water bottle and bowl to keep your dog hydrated", "en", 13);
insert into product_feature values (2, "Compartimento de almacenamiento para llevar snacks o bolsas de residuos", "es", 13);
insert into product_feature values (2, "Storage compartment to carry snacks or waste bags", "en", 13);
insert into product_feature values (3, "Diseño portátil y ligero para facilitar su transporte durante paseos o viajes", "es", 13);
insert into product_feature values (3, "Portable and lightweight design for easy carrying during walks or trips", "en", 13);
insert into product_feature values (4, "Boquilla a prueba de fugas para un uso sin derrames ni desperdicios", "es", 13);
insert into product_feature values (4, "Leak-proof nozzle for spill-free and waste-free use", "en", 13);
insert into product_feature values (5, "Materiales seguros y duraderos, aptos para el contacto con alimentos", "es", 13);
insert into product_feature values (5, "Safe and durable materials, food-grade approved", "en", 13);
insert into product_feature values (6, "Fácil de limpiar y mantener en condiciones higiénicas", "es", 13);
insert into product_feature values (6, "Easy to clean and maintain in hygienic conditions", "en", 13);
insert into product_feature values (7, "Correa integrada para colgar la botella del bolso o mochila", "es", 13);
insert into product_feature values (7, "Integrated strap for hanging the bottle on a bag or backpack", "en", 13);
insert into product_feature values (8, "Disponible en varios colores y tamaños para adaptarse a tus preferencias", "es", 13);
insert into product_feature values (8, "Available in various colors and sizes to suit your preferences", "en", 13);
insert into product_feature values (1, "Cama cómoda y portátil para que tu perro descanse en cualquier lugar", "es", 14);
insert into product_feature values (1, "Comfortable and portable bed for your dog to rest anywhere", "en", 14);
insert into product_feature values (2, "Relleno suave y acolchado para mayor comodidad y apoyo", "es", 14);
insert into product_feature values (2, "Soft and padded filling for enhanced comfort and support", "en", 14);
insert into product_feature values (3, "Diseño plegable y ligero que facilita el transporte y almacenamiento", "es", 14);
insert into product_feature values (3, "Foldable and lightweight design for easy transport and storage", "en", 14);
insert into product_feature values (4, "Material duradero y resistente que proporciona una superficie resistente a los arañazos", "es", 14);
insert into product_feature values (4, "Durable and sturdy material that provides a scratch-resistant surface", "en", 14);
insert into product_feature values (5, "Fácil de limpiar y mantener en condiciones higiénicas", "es", 14);
insert into product_feature values (5, "Easy to clean and maintain in hygienic conditions", "en", 14);
insert into product_feature values (6, "Tamaño adecuado para perros de diferentes razas y tamaños", "es", 14);
insert into product_feature values (6, "Suitable size for dogs of different breeds and sizes", "en", 14);
insert into product_feature values (7, "Bordes elevados que brindan un apoyo adicional para la cabeza y el cuello", "es", 14);
insert into product_feature values (7, "Raised edges that provide additional support for the head and neck", "en", 14);
insert into product_feature values (8, "Diseño atractivo y moderno que se adapta a la decoración de tu hogar", "es", 14);
insert into product_feature values (8, "Attractive and modern design that complements your home decor", "en", 14);
insert into product_feature values (1, "Cama cómoda y portátil para que tu perro descanse en cualquier lugar", "es", 15);
insert into product_feature values (1, "Comfortable and portable bed for your dog to rest anywhere", "en", 15);
insert into product_feature values (2, "Relleno suave y acolchado para mayor comodidad y apoyo", "es", 15);
insert into product_feature values (2, "Soft and padded filling for enhanced comfort and support", "en", 15);
insert into product_feature values (3, "Diseño plegable y ligero que facilita el transporte y almacenamiento", "es", 15);
insert into product_feature values (3, "Foldable and lightweight design for easy transport and storage", "en", 15);
insert into product_feature values (4, "Material duradero y resistente que proporciona una superficie resistente a los arañazos", "es", 15);
insert into product_feature values (4, "Durable and sturdy material that provides a scratch-resistant surface", "en", 15);
insert into product_feature values (5, "Fácil de limpiar y mantener en condiciones higiénicas", "es", 15);
insert into product_feature values (5, "Easy to clean and maintain in hygienic conditions", "en", 15);
insert into product_feature values (6, "Tamaño adecuado para perros de diferentes razas y tamaños", "es", 15);
insert into product_feature values (6, "Suitable size for dogs of different breeds and sizes", "en", 15);
insert into product_feature values (7, "Bordes elevados que brindan un apoyo adicional para la cabeza y el cuello", "es", 15);
insert into product_feature values (7, "Raised edges that provide additional support for the head and neck", "en", 15);
insert into product_feature values (8, "Diseño atractivo y moderno que se adapta a la decoración de tu hogar", "es", 15);
insert into product_feature values (8, "Attractive and modern design that complements your home decor", "en", 15);
insert into product_feature values (1, "Piscina portátil para que tu perro se refresque en los días calurosos", "es", 16);
insert into product_feature values (1, "Portable pool for your dog to cool off on hot days", "en", 16);
insert into product_feature values (2, "Construcción resistente y duradera para un uso prolongado", "es", 16);
insert into product_feature values (2, "Sturdy and durable construction for long-lasting use", "en", 16);
insert into product_feature values (3, "Fácil de montar y desmontar, sin necesidad de herramientas", "es", 16);
insert into product_feature values (3, "Easy to assemble and disassemble, no tools required", "en", 16);
insert into product_feature values (4, "Base antideslizante para mayor seguridad al entrar y salir", "es", 16);
insert into product_feature values (4, "Non-slip base for added safety when entering and exiting", "en", 16);
insert into product_feature values (5, "Tamaño adecuado para perros de diferentes razas y tamaños", "es", 16);
insert into product_feature values (5, "Appropriate size for dogs of different breeds and sizes", "en", 16);
insert into product_feature values (6, "Drenaje fácil y rápido para un vaciado sin complicaciones", "es", 16);
insert into product_feature values (6, "Easy and quick drainage for hassle-free emptying", "en", 16);
insert into product_feature values (7, "Perfecta para usar en el jardín, patio o en excursiones al aire libre", "es", 16);
insert into product_feature values (7, "Perfect for use in the garden, backyard, or outdoor excursions", "en", 16);
insert into product_feature values (8, "Proporciona diversión acuática y entretenimiento para tu perro", "es", 16);
insert into product_feature values (8, "Provides aquatic fun and entertainment for your dog", "en", 16);
